services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
  backend-svc:
    build:
      context: backend-svc
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - localstack
  pulumi:
    build:
      context: pulumi
    env_file:
      - .env
    depends_on:
      - pulumi