{{- if .Values.enableBenchmark }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.backendApiBenchmark.name }}-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.backendApiBenchmark.reportOutputAbsoluteDirPath }}
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
{{- end }}