{{- if .Values.enableBenchmark }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.backendApiBenchmark.name }}
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      labels:
        app: {{ .Values.backendApiBenchmark.name }}
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: {{ .Values.backendApiBenchmark.name }}
          image: {{ .Values.backendApiBenchmark.image }}
          securityContext:
            runAsUser: 1000
          workingDir: /output
          args:
            - run
            - --out
            - web-dashboard
            - /scripts/bench.js
          env:
            - name: K6_WEB_DASHBOARD_EXPORT
              value: report.html
            - name: TARGET_HTTP_HOSTNAME
              value: {{ .Values.backendApi.name }}
            - name: TARGET_HTTP_PORT
              value: "{{ .Values.backendApi.serviceHttpPort }}"
          volumeMounts:
            - name: k6-output
              mountPath: /output
      restartPolicy: Never
      volumes:
        - name: k6-output
          persistentVolumeClaim:
            claimName: {{ .Values.backendApiBenchmark.name }}-pvc
{{- end }}