apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-svc
  template:
    metadata:
      labels:
        app: backend-svc
    spec:
      containers:
        - name: backend-svc
          image: {{ .Values.backendApi.image }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: app-configs
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10