apiVersion: batch/v1
kind: Job
metadata:
  name: pulumi-job
spec:
  template:
    metadata:
      labels:
        app: pulumi
    spec:
      containers:
        - name: pulumi
          image: {{ .Values.pulumi.image }}
          command: 
            - sh
            - -c
            - |
              set -e
              poetry env use system
              export AWS_ENDPOINT_URL="$LOCALSTACK_HOST"
              echo $AWS_ENDPOINT_URL
              sed -i 's/http:\/\/[^:]\+:[0-9]\+/http:\/\/$LOCALSTACK_HOST/g' infra/Pulumi.backendapi.yaml
              poetry run pulumilocal cancel --stack $PULUMI_STACK_NAME --cwd infra --yes
              poetry run pulumilocal refresh --stack $PULUMI_STACK_NAME --cwd infra --yes -f
              poetry run pulumilocal up --stack $PULUMI_STACK_NAME --cwd infra --yes -f
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              chmod +x kubectl
              ./kubectl create configmap pulumi-status --from-literal=completed=true --dry-run=client -o yaml | ./kubectl apply -f -
          envFrom:
            - configMapRef:
                name: app-configs
      restartPolicy: Never
  ttlSecondsAfterFinished: 100