apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  selector:
    app: localstack
  ports:
    - protocol: TCP
      name: localstack-main-port
      port: 4566
      targetPort: 4566
    - protocol: TCP
      name: localstack-port-2
      port: 4510
      targetPort: 4510
    - protocol: TCP
      name: localstack-port-3
      port: 4559
      targetPort: 4559
