apiVersion: batch/v1
kind: Job
metadata:
  name: pulumi-job
  annotations:
    "helm.sh/hook": "post-install"
spec:
  template:
    metadata:
      labels:
        app: pulumi
    spec:
      containers:
        - name: pulumi
          image: {{ .Values.pulumi.image }}
          command: 
            - sh
            - -c
            - |
              set -e
              echo "Running Pulumi deployment at $AWS_ENDPOINT_URL"
              poetry run pulumilocal cancel --stack $PULUMI_STACK_NAME --cwd infra --yes || true
              poetry run pulumilocal refresh --stack $PULUMI_STACK_NAME --cwd infra --yes -f
              poetry run pulumilocal up --stack $PULUMI_STACK_NAME --cwd infra --yes -f
          envFrom:
            - configMapRef:
                name: app-configs
          env:
            - name: K8S_AWS_SECRET_NAME
              value: {{ .Values.backendApi.awsSecretName }}
            - name: K8S_NAMESPACE_ID
              value: {{ .Release.Namespace }}
            - name: AWS_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: app-configs
                  key: LOCALSTACK_HOST
      restartPolicy: Never
  ttlSecondsAfterFinished: 100