enableE2eTest: false

localstack:
  name: "localstack"
  image: "localstack/localstack"
  service:
    ports:
      - port: 4566
      - port: 4510-4559

backendApi:
  name: "backend-svc"
  image: "localhost:32000/backend-svc:latest"
  service:
    ports:
      - port: 8000
  awsSecretName: aws-secret
  awsServiceAccountName: aws-service-account

pulumi:
  name: "pulumi"
  image: "localhost:32000/pulumi:latest"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
